accounts/urls.py
from unicodedata import name
from django.urls import path
from .views import *
app_name='accounts'
urlpatterns = [
 
    
    path('',home,name='home'),
   # path('administration',admine,name='admine'),
    path('singup',creat_us,name='register'),
    path('logout',user_logout,name='logout'),
    path('singin',user_singin,name='login'),
    path('<str:id>',users_profile,name='profile'),
    path('pr/<str:id>',users_req,name='reequette'),
    path('prs/',users_reqe,name='requette'),
    path('up/<str:id>',update_us,name='update_us'),
    path('link/<str:id>',liens,name='liens'),
    path('apc/<str:id>',apc,name='apc'),
    path('admina/<str:id>',del_n,name='del_n'),
    #path('news/<str:id>',news,name='news'),
    #path('weather/<str:id>',index_w,name='index'),

    
]

maps/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name='maps'


urlpatterns = [
 #   path('',views.route,name='route'),
  #  path('map',views.map,name='map'),
     
]


'''
urlpatterns = [
  
    path=('',views.route,name='route'),
    path=('map',views.map,name='map'),

]
'''

projet/urls.py
from re import A
from xml.dom.minidom import Document
from django.contrib import admin
from django.http import HttpResponse
from django.urls import path,include
from accounts.views import home
from django.shortcuts import redirect, render
from django.conf.urls.static import static
from django.conf import settings
#from accounts.views import  

from projet.settings import MEDIA_URL
def about_site(request):
    return render(request,'about.html')
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('maps/',include('maps.urls',namespace='maps')),
    path('about/',about_site,name='about_us'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/profile/about.html
{%extends 'base.html'%}
{% load bootstrap4 %}

{% load static %}


{% block container %}
<div class="container">
 <a href="{% url 'accounts:home'%}"> <h1 style="color:rgb(13, 7, 29);font-size:40px;">         مـــــؤسسة شـــمــــل للبرمجيات</h1></a> 


</div>



 

 {% endblock%}

templates/profile/creation.html
{% extends 'base.html'%}
{% load bootstrap4 %}

{% block container%}
<div class="container">
<h1>مرحبا بك معنا</h1>
</div>
<div class="container">
   
    <form class="row g-3" method="POST" enctype= multipart/form-data >
        {% csrf_token %}
        <div class="row">
          <div class="col-6">
        {% bootstrap_form form_u%}
      </div>
      <div class="col-1"></div>
      <div class="col-5">
        <label for="Titre" style="color: #01060e">  رقم الهاتف  </label> <br>
        {{form_p.phone}} <br>
        <label for="Titre" style="color: #020a14">        معلومات عامة  </label><br>
        {{form_p.bio_p}} <br>
        <label for="Titre" style="color: #010408">  صورة البروفايل  </label><br>
        {{form_p.photo}} <br>
        <label for="Titre" style="color: #010408">    نوع المستخدم</label><br>
        {{form_p.list_ch}} <br>
      </div>
      </div>
        <button class="btn btn-primary" type="submit">ســـــــجـــــــل</button>
      </form>
      <br>
      <br>

    

  </div>


{% endblock%}

templates/profile/liens.html
{%extends 'base.html'%}
{% load bootstrap4 %}

{% load static %}
<script src="admine.js"></script>
{% block container %}
<head>

  <style>
      
      body {
color:black;
background-color:white;
background-image:url({% static 'images/dz.jpg'%});
background-repeat:no-repeat;
-webkit-background-size: cover; /* pour anciens Chrome et Safari */
  background-size: cover; /* version standardisée */
 background-attachment:fixed;
}
       
     
  </style>
</head>
<body>
  
  

<div class="container">
 <br>
    <div class="row row-cols-1 row-cols-md-2 g-4">
        <div class="col">
          <div class="card">             
            <img src="{%static 'images/moradia.jpg'%}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">رئاسة الجمهورية </h5>
              <p class="card-text"><span>أرقام الهاتف </span>	  021 69 15 15</p>
              <p class="card-text"> أرقام الفاكس	----------- </p>
              <p class="card-text"> عنوان الإيميل	contact@el-mouradia.dz  </p>
              <p class="card-text"> موقع الانترنت	<a href="https://www.el-mouradia.dz/ar/home" target="_blank">el-mouradia.dz</a></p>
            
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card">             
            <img src="{%static 'images/hokoma.jpg'%}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">رئــيس الحكومة  </h5>
              <p class="card-text">أرقام الهاتف	  021 73 12 00/021 73 12 00</p>
              <p class="card-text"> أرقام الفاكس	----------- </p>
              <p class="card-text"> عنوان الإيميل	   </p>
              <p class="card-text"> موقع الانترنت	<a href="https://www.premier-ministre.gov.dz/ar" target="_blank">premier-ministre.gov.dz</a></p>
            
            </div>
          </div>
        </div>
        <br>
        <div class="col">
          <div class="card">             
            <img src="{%static 'images/daflouuu.jpg'%}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">  بلدية حاسي الرمل </h5>
              <p class="card-text">أرقام الهاتف  	029 96 99 99/ 029 96 99 99</p>
              <p class="card-text"> أرقام الفاكس	029 96 55 77/029 96 55 77</p>
              <p class="card-text"> عنوان الإيميل	Apc-bellil@gmail.com   </p>
              <p class="card-text"> موقع الانترنت	<a href="http://127.0.0.1:8000/accounts/" target="_blank">Apc-bellil.com</a></p>
            
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card">             
            <img src="{%static 'images/wlaghouat.jpg'%}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">ولايــة الأغواط</h5>
              <p class="card-text">أرقام الهاتف	029 93 11 05/029 93 10 02</p>
              <p class="card-text"> أرقام الفاكس	029 93 21 22/029 93 57 57 </p>
              <p class="card-text"> عنوان الإيميل	wilaya.laghouat@gmail.com   </p>
              <p class="card-text"> موقع الانترنت	<a href="http://www.wilaya-laghouat.dz" target="_blank">http://www.wilaya-laghouat.dz</a></p>
            
            </div>
          </div>
        </div>
      </div>
      <br>
      <div class="row row-cols-1 row-cols-md-2 g-4">
        <div class="col">
          <div class="card">             
            <img src="{%static 'images/pompier.jpg'%}" class="card-img-top" alt="protection civil">
            <div class="card-body">
              <h5 class="card-title">الحماية المدنية</h5>
              <p class="card-text">أرقام الهاتف	029 93 11 05/029 93 10 02</p>
              <p class="card-text"> أرقام الفاكس	029 93 21 22/029 93 57 57 </p>
              <p class="card-text"> عنوان الإيميل	wilaya.laghouat@gmail.com   </p>
              <p class="card-text"> موقع الانترنت	<a href="http://www.wilaya-laghouat.dz" target="_blank">http://www.wilaya-laghouat.dz</a></p>
            
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card">             
            <img src="{%static 'images/dgsn.jpg'%}" class="card-img-top" alt="police laghouat">
            <div class="card-body">
              <h5 class="card-title">dgsn</h5>
              <p class="card-text">أرقام الهاتف	029 93 11 05/029 93 10 02</p>
              <p class="card-text"> أرقام الفاكس	029 93 21 22/029 93 57 57 </p>
              <p class="card-text"> عنوان الإيميل	wilaya.laghouat@gmail.com   </p>
              <p class="card-text"> موقع الانترنت	<a href="https://www.algeriepolice.dz/" target="_blank">DGSN</a></p>
            
            </div>
          </div>
        </div>
        
</div>


<br><br><br><br><br>
 

 {% endblock%}
</body>

templates/profile/login.html
{%extends 'base.html'%}
{% load bootstrap4 %}

  

{% block container %}

<div class="container">
  <h1>تسجيل الدخول</h1>
  <br>
      <br>
  <div class="container">
  <form action="" method="POST">
    {% csrf_token %}
     
    <label for="username" > اسم المستخدم  :</label>
      <input type="text" placeholder="username" name="username" aria-label="username" >
     
      <br>
      <br>
      <label for="username" >  كـلمة المـرور    :</label>
      <input type="password"  name="password" placeholder="password" aria-label="password" > <br>
      <br>
      <br>
    <button class="btn btn-primary" type="submit">   تسجيل الدخول</button> <br>
    <a href="{% url 'accounts:register'%}">  اذا كنت لا تملك حسابا سجل الان</a>

    
  </form>
</div>
</div>
{% endblock%}

templates/profile/profile.html
{%extends 'base.html'%}
{% load bootstrap4 %}

  

{% block container %}
<h1>صفحة المعلومات الشخصية للمستخدم {{user}}</h1>
<div class="row">
  <div class="col-sm-9"> 
       <div class="container">
            <br><hr>
            <h1> {{util}}</h1> <br>
            <hr>---- <br>
            <div class="container">
           
   
<h2>
             <label for="">  الاسم   :  </label>{{util.first_name}} 
           <br> <br>
             <label for="">  اللقب :  </label>  {{util.last_name}} <br> <br>
             {% for i in prof %}
             <label for=""> رقم الهاتف   :  </label>  {{i.phone}} 
              
              
 
 
           {% endfor %}
           <br> <br>
           <label for="">  البريد الالكتروني   :  </label>   {{util.email}} <br> <br></h2>
                 <a href="{% url 'accounts:update_us' user.id %}"> تعديل</a>
         </div>
        <hr>---- <br>
      </div>
        

  </div>
  <div class="col-sm-3"> 
    {% for i in prof %}
    <img src="{{i.photo.url}}">
    {% endfor %}
  </div>
</div>
{% endblock%}

templates/profile/requette.html
{%extends 'base.html'%}
{% load bootstrap4 %}
{% load static %}
  

{% block container %}
<style>
      
  body {
color:black;
background-color:white;
background-image:url({% static 'images/Marché_dAflou,_1973.jpg'%});
background-repeat:no-repeat;
-webkit-background-size: cover; /* pour anciens Chrome et Safari */
background-size: cover; /* version standardisée */
background-attachment:fixed;

}
   
 
</style>
<center>
<h1 style="color: #edeef5">ارسال رساله الى السيد رئيس البلدية</h1>
</center>
<div class="container">
  <hr>
  <form action="" method="POST" enctype= multipart/form-data>
    {% csrf_token%}
  {{ form.media }}
  <label for="Titre" style="color: #e9eef5">  عنوان الرسالة</label>
  
  {{form.Titre}} <br><br>
   
    <label for="Titre" style="color: #e9eef5"> موضوع متصل  بقطع الاراضي  </label>
    {{form.lot_terrain}}
   
  
  <br><br>
  <label for="Titre"> </label>
  {{form.content}}<br><br>
  <label for="Titre" style="color: #e9eef5">  ارفاق ملف</label>
  {{form.join_f}}<br><br>
  <label for="Titre" style="color: #e9eef5">  ارفاق صورة</label>
  {{form.photo}}
  
  <hr> 
  <button class="btn btn-primary" type="submit">ارسال</button>
  <hr>  <br>
</form>

</div>

  
{% endblock%}

templates/profile/requettes.html
{%extends 'base.html'%}
{% load bootstrap4 %}
{% load static %}
  

{% block container %}
<style>
      
  body {
color:black;
background-color:white;
background-image:url({% static 'images/Marché_dAflou,_1973.jpg'%});
background-repeat:no-repeat;
-webkit-background-size: cover; /* pour anciens Chrome et Safari */
background-size: cover; /* version standardisée */
background-attachment:fixed;

}
   
 
</style>
<center>
<h1 style="color: #edeef5">ارسال رساله الى السيد رئيس البلدية</h1>
</center>
<div class="container">
  <hr>
  <form action="" method="POST" enctype= multipart/form-data>
    {% csrf_token%}
    {{ form.media }}
    {%bootstrap_form form%}
     <!--
     /*{{ form.media }}
     /*<label for="Titre" style="color: #e9eef5">  عنوان الرسالة</label>
     /*{{form.Titre}}<br><br>
     /* <label for="Titre"> </label>
     /* {{form.content}}<br><br>
     /* <label for="Titre" style="color: #e9eef5">  ارفاق ملف</label>
     /* {{form.join_f}}<br><br>
     /* <label for="Titre" style="color: #e9eef5">  ارفاق صورة</label>
     /* {{form.photo}}*/
   -->
  <hr> 
  <button class="btn btn-primary" type="submit">ارسال</button>
  <hr>  <br>
</form>

</div>

  
{% endblock%}

templates/profile/update.html
{%extends 'base.html'%}
{% load bootstrap4 %}

  

{% block container %}
<h1>صفحة المعلومات الشخصية للمستخدم {{user}}</h1>
<div class="container">
  <br><hr>
  <h1> {{util}}</h1> <br>
  <hr>---- <br>
  {% for i in prof %}
  <h3>Numero de telephone  :</h3> {{i.phone}} 
  <hr>---- <br>
  {{i.liste_util}}
  <hr>---- <br>
  <img src="{{i.photo.url}}">  <br>
  
  
  {% endfor %}

   

  {{util.first_name}} <br>
  {{util.last_name}} <br>
  {{util.email}} <br>
 
  <hr>---- <br>
<a href="{% url 'accounts:update_us' user.id %}"></a>

</div>

  
{% endblock%}