accounts/urls.py
from unicodedata import name
from django.urls import path
from .views import *
app_name='accounts'
urlpatterns = [
 
    
    path('',home,name='home'),
   # path('administration',admine,name='admine'),
    path('singup',creat_us,name='register'),
    path('logout',user_logout,name='logout'),
    path('singin',user_singin,name='login'),
    path('<str:id>',users_profile,name='profile'),
    path('pr/<str:id>',users_req,name='reequette'),
    path('prs/',users_reqe,name='requette'),
    path('up/<str:id>',update_us,name='update_us'),
    path('link/<str:id>',liens,name='liens'),
    path('apc/<str:id>',apc,name='apc'),
    path('admina/<str:id>',del_n,name='del_n'),
    #path('news/<str:id>',news,name='news'),
    #path('weather/<str:id>',index_w,name='index'),

    
]

maps/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name='maps'


urlpatterns = [
 #   path('',views.route,name='route'),
  #  path('map',views.map,name='map'),
     
]


'''
urlpatterns = [
  
    path=('',views.route,name='route'),
    path=('map',views.map,name='map'),

]
'''

projet/urls.py
from re import A
from xml.dom.minidom import Document
from django.contrib import admin
from django.http import HttpResponse
from django.urls import path,include
from accounts.views import home
from django.shortcuts import redirect, render
from django.conf.urls.static import static
from django.conf import settings
#from accounts.views import  

from projet.settings import MEDIA_URL
def about_site(request):
    return render(request,'about.html')
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('maps/',include('maps.urls',namespace='maps')),
    path('about/',about_site,name='about_us'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about.html
{%extends 'base.html'%}
{% load bootstrap4 %}

{% load static %}


{% block container %}
<style>
      
    body {
color:black;
background-color:white;
background-image:url({% static 'images/Marché_dAflou,_1973.jpg'%});
background-repeat:no-repeat;
-webkit-background-size: cover; /* pour anciens Chrome et Safari */
background-size: cover; /* version standardisée */
background-attachment:fixed;

} 
</style>
<center>
<div class="container">
 <a href="{% url 'accounts:home'%}"> <h1 style="color:rgb(242, 241, 245);font-size:40px;">  مـــــؤسسة شـــمــــل للبرمجيات</h1></a> 
</div>
</center>
{% endblock%}

templates/admin1.html
{% extends "administration.html" %}


<div class="container">
sqfdsfsqdfsdf
 <form class="row g-3" method="POST" enctype= multipart/form-data >
  {%csrf_token%}
<label for="form_n.page_n" style="color:rgb(249, 248, 252);font-size:20px;"> عنوان الصفحة      :</label> 
{{form_n.page_n}} <br><br><br>
<label for="form_n.page_n" style="color:rgb(249, 248, 252);font-size:20px;"> صورة الصفحة         :</label> 
{{form_n.photo_n}} <br><br><br>
<label for="form_n.page_n" style="color:rgb(249, 248, 252);font-size:20px;"> وصف الصفحة     :</label>  
{{form_n.desc_n}} <br><br><br>
<button class="btn btn-primary" type="submit">  حــــــفظ</button> <br>
</form>
       <!--<div class="card" style="width: 18rem;">
         <div class="card-header">
         ادواة الادارة
         </div>
           <ul class="list-group list-group-flush">
            <a href="#"> <li class="list-group-item"> جديد الموقع</li></a>
            <a href="#"><li class="list-group-item">رسائل و شكاوى الموطنين</li></a>
            <a href="#"><li class="list-group-item">تاكيد موعيد الاستقبال</li></a>
          </ul>
       </div> 
      </div>

      <div class="col-8">
-----------------------------
<form class="row g-3" method="POST" enctype= multipart/form-data >
  {%csrf_token%}
<label for="form_n.page_n" style="color:rgb(249, 248, 252);font-size:20px;"> عنوان الصفحة      :</label> 
{{form_n.page_n}} <br><br><br>
<label for="form_n.page_n" style="color:rgb(249, 248, 252);font-size:20px;"> صورة الصفحة         :</label> 
{{form_n.photo_n}} <br><br><br>
<label for="form_n.page_n" style="color:rgb(249, 248, 252);font-size:20px;"> وصف الصفحة     :</label>  
{{form_n.desc_n}} <br><br><br>
<button class="btn btn-primary" type="submit">  حــــــفظ</button> <br>
</form>
----------------------
      </div>-->
    </div>

templates/admin2.html
{%extends 'base.html'%}
{% load bootstrap4 %}

{% load static %}


{% block container %}
<style>
      
    body {
color:black;
background-color:white;
background-image:url({% static 'images/Marché_dAflou,_1973.jpg'%});
background-repeat:no-repeat;
-webkit-background-size: cover; /* pour anciens Chrome et Safari */
background-size: cover; /* version standardisée */
background-attachment:fixed;


}


</style>
<center>
<div class="container">
  <a href="{% url 'accounts:home'%}"> <h1 style="color:rgb(249, 248, 252);font-size:40px;"> صفحة الادارة</h1></a> 
  <!--
  {% for n in news  %} 
 {{n.desc_n}} <br>
 {{n.created_n}} <br>
 {% endfor %} 
 -->
 </div>
</center>
 <div class="container">
    <div class="row">
      <div class="col-10">

        <ul class="nav nav-tabs">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Active</a>
            
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
       <!--<div class="card" style="width: 18rem;">
         <div class="card-header">
         ادواة الادارة
         </div>
           <ul class="list-group list-group-flush">
            <a href="#"> <li class="list-group-item"> جديد الموقع</li></a>
            <a href="#"><li class="list-group-item">رسائل و شكاوى الموطنين</li></a>
            <a href="#"><li class="list-group-item">تاكيد موعيد الاستقبال</li></a>
          </ul>
       </div> 
      </div>

      <div class="col-8">
-----------------------------
<form class="row g-3" method="POST" enctype= multipart/form-data >
  {%csrf_token%}
<label for="form_n.page_n" style="color:rgb(249, 248, 252);font-size:20px;"> عنوان الصفحة      :</label> 
{{form_n.page_n}} <br><br><br>
<label for="form_n.page_n" style="color:rgb(249, 248, 252);font-size:20px;"> صورة الصفحة         :</label> 
{{form_n.photo_n}} <br><br><br>
<label for="form_n.page_n" style="color:rgb(249, 248, 252);font-size:20px;"> وصف الصفحة     :</label>  
{{form_n.desc_n}} <br><br><br>
<button class="btn btn-primary" type="submit">  حــــــفظ</button> <br>
</form>
----------------------
      </div>-->
    </div>

</div>
<br><br><br>
 

 {% endblock%}

templates/administration.html
{%extends 'base.html'%}
{% load bootstrap4 %}

{% load static %}

{% block container %}
<style>
      
    body {
color:black;
background-color:white;
background-image:url({% static 'images/Marché_dAflou,_1973.jpg'%});
background-repeat:no-repeat;
-webkit-background-size: cover; /* pour anciens Chrome et Safari */
background-size: cover; /* version standardisée */
background-attachment:fixed;
}
button{
  cursor: pointer;
  border-radius: 50px;
  border: none;

}
label{

  color: rgb(241, 231, 231);
}
#lettres {

  display: none;
}
#check{
display: none;

}
#news{
 display: none;

 padding: 4;
}
 




</style>
<center>
<div class="container">
  <a href="{% url 'accounts:home'%}"> <h1 style="color:rgb(249, 248, 252);font-size:40px;"> صفحة الادارة</h1></a> 
  <!--
  {% for n in news  %} 
 {{n.desc_n}} <br>
 {{n.created_n}} <br>
 {% endfor %} 
 -->
 </div>
</center>
 <div class="container">
    <div class="row">
      <div class="col-6">

        
       <!----><div class="card" style="width: 18rem;">
         <div class="card-header">
         ادوات الادارة
         </div>
           <ul class="list-group list-group-flush">
             <li class="list-group-item"> <button id="b1" >جديد الموقع</button> </li>
            <li class="list-group-item"><button id="b2">رسائل و شكاوى المواطنين</button></li>
            <li class="list-group-item"><button id="b3" >تاكيد مواعيد الاستقبال</button></li>
          </ul>
       </div> 
      </div>

   <div class="col-6">
-----------------------------
        <div id="news">
          <button id="baddl" >   اضافة    </button>
          <button id="breml" >    حذف   </button>
          <div id="addl">     
            <form class="row g-3" method="POST" enctype= multipart/form-data >
              {%csrf_token%}
            <label for="form_n.page_n" style="color:rgb(249, 248, 252);font-size:20px;"> عنوان الصفحة      :</label> 
            {{form_n.page_n}} <br><br><br>
            <label for="form_n.page_n" style="color:rgb(249, 248, 252);font-size:20px;"> صورة الصفحة         :</label> 
            {{form_n.photo_n}} <br><br><br>
            <label for="form_n.page_n" style="color:rgb(249, 248, 252);font-size:20px;"> وصف الصفحة     :</label>  
            {{form_n.desc_n}} <br><br><br>
            <button class="btn btn-primary" type="submit">  حــــــفظ</button> <br>
            </form>
          </div>    
          <div id="reml">    <br>
          
            {% for n in new_to_del  %}
              <a href="{% url 'accounts:del_n' n.id %}"> {{n.id}}{{n.desc_n}} </a><br>
            {% endfor %}
          
          
          
          </div>
      </div>
      ---------------------------
      <div id="lettres">
        <button id="b5" >   كل الرسائل</button>
                <button id="b4" >    قطع اراضي </button>
                <button id="b6" >     جمعيات المجتمع المدني</button>
                <button id="b7" >      هيئات نظامية </button>
                <button id="b8" >   موظف بلدية  </button>
                <button id="b9" >    مواطنين   </button>
                 
            

                <div id="lots">
                          
                          
                            <h1>lettres </h1>
                          {%for re in req_f%}
                          <label for="titre">   المرسل :</label> 
                          {{re.userr}}   <br>
                          <label for="titre">    البريد الالكتروني :</label> 
                          {{re.userr.email}}   <br>
                          <label for="titre"> عنوان الرسالة</label> 
                          {{re.Titre}}   <br>
                          <label for="created_r">   تاريخ الارسال</label> 
                          {{re.created_r}} <br>
                          <label for="join_f">   ملفات مرفقه</label> 
                          {{re.join_f}}        <br>
                          <label for="photo">   صورة مرفقه</label> 
                          {{re.photo}}<br>
                          <hr>
                          {%endfor%}
                        
                   
                        
                </div>
                <div id="slots">
                <h1>lettres </h1>
                {%for r in req%}
                <label for="titre">   المرسل :</label> 
                {{r.userr}}   <br>
                <label for="titre">   البريد الالكتروني :</label> 
                {{r.userr.email}}   <br>
                <label for="titre"> عنوان الرسالة</label> 
                {{r.Titre}}   <br>
                <label for="created_r">   تاريخ الارسال</label> 
                {{r.created_r}} <br>
                <label for="join_f">   ملفات مرفقه</label> 
                {{r.join_f}}        <br>
                <label for="photo">   صورة مرفقه</label> 
                {{r.photo}}<br>
                <hr>
                {%endfor%}
              </div>
              <div id="asso">

                  <h1>association</h1>
                  {% for ass in  req_ass_l%}
                  <label for="titre">   المرسل :</label> 
                {{ass.user}}   <br>
                <label for="titre">   البريد الالكتروني :</label> 
                {{ass.user.email}}   <br>
                <label for="titre">  phone</label> 
                {{ass.phone}}   <br>
                <label for="created_r">   تاريخ الارسال</label> 
                {{ass.created_r}} <br>
                <label for="join_f">   ملفات مرفقه</label> 
                {{ass.join_f}}        <br>
                <label for="photo">   صورة مرفقه</label> 
                {{ass.photo}}<br>
                <hr>
                  
                  {% endfor %}
              </div>
              <div id="organ">
                  <h1>organistation</h1>
              </div>
              <div id="apc">
                  <h1> apc</h1>
              </div>
              <div id="cito">
                  <h1> cotoyens</h1>
              </div>
      </div>
      ------------------------------------
      <div id="check">
        <h1>check</h1>
      </div>
----------------------
  </div>
    </div>

</div>
<br><br><br>
<script src="jquery/jquery-3.6.0.min.js"></script>
<script>
/*  
if ($('#isSelected').attr('checked')) {
  $("#divShow").show();
} else {
  $("#divHide").hide();
}
                  */

  $(document).ready(function(){
    $('#b1').click(function(){
      $('#news').show()
      $('#lettres').hide()
      $('#check').hide()

  });
  $('#b2').click(function(){
      $('#news').hide()
      $('#lettres').show()
      $('#check').hide()
  });
  $('#b3').click(function(){
      $('#news').hide()
      $('#lettres').hide()
      $('#check').show()

  });

  /*
  <div id="asso"></div>
              <div id="organ"></div>
              <div id="apc"></div>
              <div id="cito"></div>

  */
  $('#b4').click(function(){
      $('#lots').show()
      $('#slots').hide()
      $('#organ').hide()
      $('#asso').hide()
      $('#apc').hide()
      $('#cito').hide()
      
       

  });
  $('#b5').click(function(){
      $('#lots').hide()
      $('#slots').show()
      $('#organ').hide()
      $('#asso').hide()
      $('#apc').hide()
      $('#cito').hide()
       

  });
  $('#b6').click(function(){
      $('#lots').hide()
      $('#slots').hide()
      $('#organ').hide()
      $('#asso').show()
      $('#apc').hide()
      $('#cito').hide()
       

  });
  $('#b7').click(function(){
      $('#lots').hide()
      $('#slots').hide()
      $('#organ').show()
      $('#asso').hide()
      $('#apc').hide()
      $('#cito').hide()

  });
  $('#b8').click(function(){
      $('#lots').hide()
      $('#slots').hide()
      $('#organ').hide()
      $('#asso').hide()
      $('#apc').show()
      $('#cito').hide()


  });
  $('#b9').click(function(){
      $('#lots').hide()
      $('#slots').hide()
      $('#organ').hide()
      $('#asso').hide()
      $('#apc').hide()
      $('#cito').show()

       

  });
  $('#baddl').click(function(){
      $('#addl').show()
      $('#reml').hide()
      

  });
  $('#breml').click(function(){
      $('#addl').hide()
      $('#reml').show()
      

  });
  })


</script>

 {% endblock%}

templates/base.html
{% load static %}
<header>
<html lang="ar" dir="rtl">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" >
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" ></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
    <style>
      .dropdown:hover > .dropdown-menu {
    display: block;
}
.dropdown > .dropdown-toggle:active {
    /*Without this, clicking will make it sticky*/
    pointer-events: none;
}
    </style>
  </header>
<nav class="navbar navbar-expand-lg navbar-light bg-light" navbar-right>


    <div class="container-fluid"> 
      <a class="navbar-brand" href="{%url 'accounts:home'%}"> <img src="{% static 'images/apc.jpg'%}" width="30" height="30" alt="">  </a>
     
      <div class="collapse navbar-collapse" id="navbarSupportedContent" > 
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          
          <li class="nav-item">  
           <hr>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{%url 'accounts:home'%}">الرئيسية</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="#"> اخبار و مستجدات وطنية  </a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="#">اعلانات و بيانات   </a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:liens' user.id %}"> روابط و ارقام مهمة </a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              الشباك الالكنروني
            </a>
            
            <ul class="dropdown-menu">
              
              <li><a class="dropdown-item" href="https://services.interieur.gov.dz/Autorisation" target="_blank"> طلب رخصة</a></li>
              <li><a class="dropdown-item" href="https://prestations.interieur.gov.dz/association/" target="_blank">طلب تسجيل التصريح التأسيسي للجمعيات البلدية و لجان الأحياء</a></li>                       
              
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="https://passeport.interieur.gov.dz/Ar/Accueil/Accueil" target="_blank">جواز السفر البيومتري  </a></li>           
              <li><a class="dropdown-item" href="https://macnibe.interieur.gov.dz/WFDefaultAr.aspx" target="_blank"> بطاقة التعريف الوطنية البيومترية    </a></li>
              <li><a class="dropdown-item" href="https://etatcivil.interieur.gov.dz/" target="_blank"> شهادة الميلاد  </a></li>
              <li><a class="dropdown-item" href="https://etatcivil.interieur.gov.dz/ActeMariage/" target="_blank">  عقد الزواج  </a></li>
              <li><a class="dropdown-item" href="https://etatcivil.interieur.gov.dz/ActeDeces/" target="_blank"> شهادة وفاة   </a></li>
            </ul>
            
            
          </li>
         
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="true">
              خدمـات
            </a>
            
            <ul class="dropdown-menu">
              {% if user.is_authenticated %}
              <li><a class="dropdown-item" href="{% url 'accounts:profile' user.id %}">عرض الملف الشخصي</a></li>
              <li><a class="dropdown-item" href="{% url 'accounts:reequette'  user.id %}">رساله الى السيد رئيس البلدية</a></li>
              <li><a class="dropdown-item" href="{% url 'accounts:profile' user.id %}"> حجز موعد استقبال مع رئيس البلدية</a></li>
              {% if user.username == 'apckhaled'%}
              <li><a class="dropdown-item" href="{% url 'accounts:apc' user.id %}">ادارة الموقع</a></li>
              {%endif%}
              <li><hr class="dropdown-divider"></li>
              {% endif%}
              <li><a class="dropdown-item" href="{% url 'about_us'  %}"> حول الموقع</a></li>
            </ul>
            
            {% if user.is_authenticated %}
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:profile' user.id %}"> مرحبا بك يا  :   {{ user}}</a>
          </li>
          {% else %}
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:register'%}">التسجيل على الموقع</a>
          </li>
          {% endif%}                  
          
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:logout'%}"> الخـروج </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login'%}"> تسجيل الدخول</a>
          </li>
          {% endif%}
          {% if user.is_authenticated %}
              <a class="nav-link" href="{% url 'accounts:reequette'  user.id %}">اتصل بنا</a>
              {% else %}
              <a class="nav-link" href="{% url 'accounts:login'  %}">     يجب التسجيل للتواصل معنا</a>
              {% endif%}
        </ul>
        {% if user.username == 'apckhaled'%}
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>

        {% else %}
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success nav-link disabled" type="submit">Search</button>
        </form>
        {% endif%}
      </div>
    </div>
  </nav>
  
  {% block container %}

  {% endblock%}
  
    <!-- Remove the container if you want to extend the Footer to full width. -->

  <!-- Remove the container if you want to extend the Footer to full width. 

  <footer class="text-center text-lg-start fixed-bottom" style="background-color: #c7c0f1;">
    <!-- Copyright 
    <div class="container d-flex justify-content-center py-3">
      <button type="button" class="btn btn-primary btn-lg btn-floating mx-2" style="background-color: #54456b;">
        <i class="fab fa-facebook-f"></i>
      </button>
      <button type="button" class="btn btn-primary btn-lg btn-floating mx-2" style="background-color: #54456b;">
        <i class="fab fa-youtube"></i>
      </button>
      
      <button type="button" class="btn btn-primary btn-lg btn-floating mx-2" style="background-color: #54456b;">
        <i class="fab fa-twitter"></i>
      </button>
    </div>
  
   
    <div class="text-center text-white p-3" style="background-color: rgba(78, 87, 79, 0.2);">
      © 2022 Copyright:
      <a class="text-white" href="http://127.0.0.1:8000/">Apc-Hassi R'mel - Bellil.com</a>
    </div>
    
  </footer> -->
  
<!-- 
  <!-- Remove the container if you want to extend the Footer to full width. -->
<div class="container my-2">
  <!-- Footer -->
  <footer class="text-center text-white fixed-bottom" style="background-color: #5160b6">
    <!-- Grid container -->
    <div class="container">
      <!-- Section: Links -->
      <section class="mt-2">
        <!-- Grid row-->
        <div class="row text-center d-flex justify-content-center pt-2">
          <!-- Grid column -->
          <div class="col-md-1">
            <h6 class="text-uppercase font-weight-bold">
              <a href="{% url 'about_us'  %}" class="text-white">حول الموقع</a>
            </h6>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-2">
            <h6 class="text-uppercase font-weight-bold">
              <a href="https://www.facebook.com/profile.php?id=100033449670960" target="_blank" class="text-white">صفحتنا على الفيسبوك</a>
            </h6>
          </div>
          <!-- Grid column -->

          
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-1">
            <h6 class="text-uppercase font-weight-bold">
              <a href="#!" class="text-white">مساعدة</a>
            </h6>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-2">
            <h6 class="text-uppercase font-weight-bold">
              {% if user.is_authenticated %}
              <a href="{% url 'accounts:reequette'  user.id %}" class="text-white">اتصل بنا</a>
              {% else %}
              <a href="{% url 'accounts:login'  %}" class="text-white">     يجب التـسجيل للتواصل معنا</a>
              {% endif%}
            </h6>
          </div> <br>
          
      <a class="text-white" href="http://127.0.0.1:8000/accounts/"
         >© 2022 Copyright : Apc-Hassi-rmel.com</a
        >
          <!-- Grid column -->
        </div>
        <!-- Grid row-->
      </section>
      <!-- Section: Links -->

      <!-- Section: Text -->
      
      <!-- Section: Text -->

      <!-- Section: Social -->
      {% if user.username == 'apckhaled'%}
      <a href="https://www.compteurdevisite.com" title="compteur site web html"><img src="https://counter5.optistats.ovh/private/compteurdevisite.php?c=xh6nz5cquplqed67srkpr9j8kzs16w3a" border="0" title="compteur site web html" alt="compteur site web html"></a>
      <!-- Section: Social -->
      {% endif %}
    </div>
    <!-- Grid container -->

    <!--  
    <div
         class="text-center p-3"
         style="background-color: rgba(0, 0, 0, 0.2)"
         >
      
    </div>
    Copyright -->
  </footer>
  <!-- Footer -->
</div>
<!-- End of .container -->
<script src="jquery/jquery-3.6.0.min.js">
function toggleDropdown (e) {
  const _d = $(e.target).closest('.dropdown'),
    _m = $('.dropdown-menu', _d);
  setTimeout(function(){
    const shouldOpen = e.type !== 'click' && _d.is(':hover');
    _m.toggleClass('show', shouldOpen);
    _d.toggleClass('show', shouldOpen);
    $('[data-toggle="dropdown"]', _d).attr('aria-expanded', shouldOpen);
  }, e.type === 'mouseleave' ? 300 : 0);
}

$('body')
  .on('mouseenter mouseleave','.dropdown',toggleDropdown)
  .on('click', '.dropdown-menu a', toggleDropdown);
</script>


<!-- End of .container -->
 